name       : python-nbclient
version    : 0.5.13
release    : 1
source     :
    - https://files.pythonhosted.org/packages/source/n/nbclient/nbclient-0.5.13.tar.gz : 40c52c9b5e3c31faecaee69f202b3f53e38d7c1c563de0fadde9d7eda0fdafe8
homepage   : https://jupyter.org
license    : BSD-3-Clause
component  : programming.python
summary    : A client library for executing notebooks
description: |
    NBClient lets you execute notebooks. A client library for programmatic notebook execution, NBClient is a tool for running Jupyter Notebooks in different execution contexts, including the command line.
builddeps  :
    - python-build
    - python-installer
rundeps    :
    - python-jupyter_client
    - python-nest-asyncio
    - python-nbformat
setup      : |
    %python3_setup
install    : |
    %python3_install
