name       : python-nbclient
version    : 0.6.3
release    : 3
source     :
    - https://files.pythonhosted.org/packages/source/n/nbclient/nbclient-0.6.3.tar.gz : b80726fc1fb89a0e8f8be1e77e28d0026b1e8ed90bc143c8a0c7622e4f8cdd9e
homepage   : https://jupyter.org
license    : BSD-3-Clause
component  : programming.python
summary    : A client library for executing notebooks
description: |
    NBClient lets you execute notebooks. A client library for programmatic notebook execution, NBClient is a tool for running Jupyter Notebooks in different execution contexts, including the command line.
builddeps  :
    - python-build
    - python-installer
rundeps    :
    - python-jupyter_client
    - python-nest-asyncio
    - python-nbformat
setup      : |
    %python3_setup
install    : |
    %python3_install
