name       : python-nbclient
version    : 0.6.7
release    : 5
source     :
    - https://files.pythonhosted.org/packages/source/n/nbclient/nbclient-0.6.7.tar.gz : 3c5a7fc6bb74be7d31edf2817b44501a65caa99e5e56363bc359649b97cd24b9
homepage   : https://jupyter.org
license    : BSD-3-Clause
component  : programming.python
summary    : A client library for executing notebooks
description: |
    NBClient lets you execute notebooks. A client library for programmatic notebook execution, NBClient is a tool for running Jupyter Notebooks in different execution contexts, including the command line.
builddeps  :
    - python-build
    - python-installer
rundeps    :
    - python-jupyter_client
    - python-nest-asyncio
    - python-nbformat
setup      : |
    %python3_setup
install    : |
    %python3_install
